### ISSUE TITLE
The bot doesn't support usernames with underscores

### ISSUE THREAD

**Issue by ChipWolf** [Markus-Rost/discord-wiki-bot#103]
One of our users is `User:PlayGamesAllDay YT` on the wiki after registering with an underscore, MediaWiki converted it to a space on most of their userpages. However, the bot refuses to verify them with or without a space/underscore in the verify command stating the username is invalid.

**Comment by Markus-Rost** [comment]
This should be an issue, are you sure the name is correct? It's case-sensitive.
Can you link their user page for me so I can take a closer look?

**Comment by ChipWolf** [comment]
https://wiki.minecraftathome.com/wiki/User:PlayGamesAllDay_YT/Discord

**Comment by Markus-Rost** [comment]
Both `!wiki User:PlayGamesAllDay YT` and `!wiki verify PlayGamesAllDay YT` return the user correctly for me.

**Comment by Markus-Rost** [comment]
This has been resolved.
