### ISSUE TITLE
Change wiki user rights based on Discord roles

### ISSUE THREAD

**Issue by ChipWolf** [Markus-Rost/discord-wiki-bot#104]
I know verification is currently unidirectional where discord roles are granted for a specific status on the wiki, however, we'd like to manipulate wiki user groups with discord roles by assigning/removing them from users.

**Comment by TreeIsLife2** [comment]
It is possible. You can manipulate min edits, ranks, account age, etc.

**Comment by Markus-Rost** [comment]
This would require the bot to login, which it doesn't do at the moment. 
I have been looking into logging in, but I would have to login for every single wiki using a bot password. The account would also need to have extended permissions on the wiki to be able change user groups.

This is not something I'll add as there also wouldn't be a good way to remove user groups again. The bot won't change anything on the wiki.

**Comment by TreeIsLife2** [comment]
So, we know what will happen now :/

**Comment by ChipWolf** [comment]
> This is not something I'll add as there also wouldn't be a good way to remove user groups again.
How so?

What kind of bounty do you want to do this? We need this functionality.
