### ISSUE TITLE
Create a file with all results from given search

### ISSUE THREAD

**Issue by Friskygote** [Markus-Rost/discord-wiki-bot#11]
**Description**: If specific mode is called, the bot will respond with a .txt file containing all pages that match the search phrase. 

**Use case**: I need to find all pages that have certain phrase and feed the .txt to a bot to do automated tasks on them, I execute the command and easily get the .txt file with all of the pages that contain given code.

**Comment by Markus-Rost** [comment]
Won't do as it's very specific and not useful for most user, but `!wiki search` now shows some search results.

But please have a cookie: 🍪🐐
