### ISSUE TITLE
It uses "Discord name" for "Wiki Name"

### ISSUE THREAD

**Issue by Zacatero** [Markus-Rost/discord-wiki-bot#110]
When you successfully !verify, it says "Discord User:" and then "Wiki User:" but it shows the same thing twice, both the discord username and discriminator.

**Comment by Sidemen19** [comment]
I recall Markus stating that is intended a while back. Confusing, as it may be for some users, it's not a bug.

**Comment by Markus-Rost** [comment]
Under "Wiki user" is the Discord tag from the wiki profile. "Discord user" provides the tag from the Discord user for comparison. 
It's more clear to see the difference when the user doesn't match.

I know it's not ideal, but I don't really know a better title for the field.

**Comment by Zacatero** [comment]
> Under "Wiki user" is the Discord tag from the wiki profile. "Discord user" provides the tag from the Discord user for comparison.
> It's more clear to see the difference when the user doesn't match.
> 
> I know it's not ideal, but I don't really know a better title for the field.

Okay that makes more sense. Thanks for letting me know!
