### ISSUE TITLE
Suggestion for Fandom Discussions

### ISSUE THREAD

**Issue by Zacatero** [Markus-Rost/discord-wiki-bot#124]
I'm not sure how much the bot can see as far as /f discussions, but an idea I had would be perhaps to have a configuration on Discord where you can set an admin channel, and then if somebody reports a reply on the discussions, the bot will send a message to that channel alerting the admins.

**Comment by Markus-Rost** [comment]
The bot is a logged out user and therefore can't see if a post is reported.

**Comment by Markus-Rost** [comment]
This would be a function for RcGcDw, which can log in.
I created https://gitlab.com/piotrex43/RcGcDw/-/issues/170 as a follow up.
