### ISSUE TITLE
Annoucements

### ISSUE THREAD

**Issue by TreeIsLife2** [Markus-Rost/discord-wiki-bot#126]
I suggest adding annoucements into Wiki-Bot, which may be

1. Send one time at some time (ex. you can set to send that annoucement at 8pm)
2. Send messages periodically (ex. every 10 minutes)

I think, it will be really great addition.

**Comment by Markus-Rost** [comment]
I don't see this as being in the scope of the bot as it is a wiki related bot.

There are also a lot of existing bots that do that very well.

**Comment by TreeIsLife2** [comment]
(Note: Gamepedia users still does not have annoucements)
