### ISSUE TITLE
WikiApari support

### ISSUE THREAD

**Issue by TreeIsLife2** [Markus-Rost/discord-wiki-bot#152]
Reason is pretty obvious

**Comment by Markus-Rost** [comment]
I don't know what WikiApiari is, but if you are referring to [WikiApiary](https://wikiapiary.com/), they use MediaWiki 1.29.1 so you should be able to set them as wiki normally but it might not work properly as Wiki-Bot is made with 1.30+ in mind.

**Comment by TreeIsLife2** [comment]
Yes, but it cannot really read from these pages

**Comment by Markus-Rost** [comment]
I'm not familiar with WikiApiary and SMW so unless you know what info you want me to show and where to get that info I probably won't add support for it, considering they are also using an older MediaWiki version and it would probably be only used rarely.

**Comment by TreeIsLife2** [comment]
Probably yes, i will close it, but consider adding it sometime in future 😉
