### ISSUE TITLE
Use embed in messages

### ISSUE THREAD

**Issue by fredster33** [Markus-Rost/discord-wiki-bot#460]
It'd be nice if WikiBot could output an embed when it sends links. This allows people (especially lurkers) to get a basic understanding of what the page is about without needing to click on the link. Here's a mockup:

![image](https://github.com/Markus-Rost/discord-wiki-bot/assets/64927044/2819af28-4cf5-4599-8f97-23723e211b1f)

**Comment by Markus-Rost** [comment]
Wiki-Bot already does that
* for slash commands unless specifically disabled
* for `!wiki` commands unless `<>` are used
* for `{{}}` inline syntax

Only the `[[]]` inline syntax doesn't show embeds, as is intended.
