### ISSUE TITLE
How to change database to mongodb

### ISSUE THREAD

**Issue by jahsenn** [Markus-Rost/discord-wiki-bot#503]

**Comment by Markus-Rost** [comment]
MongoDB is a NoSQL database, so you would have to update every single database query from SQL to MongoDB.

**Comment by Friskygote** [comment]
Or in other words, Wiki-Bot project does not support any other database than Postgres for the time being. Changing the database to any other database system will require changing the code of the project itself. In case of SQL based databases - a lot less than in case of NoSQL databases like Mango, for which you'd likely have to do major refactoring.
