### ISSUE TITLE
Wiki-bot does not understand the comments extension

### ISSUE THREAD

**Issue by OAuthority** [Markus-Rost/discord-wiki-bot#511]
This is not a major issue, because the use of Extension:Comments is neither here nor there, but for wikis that are using it and using Wiki-bot to post to Discord, it doesn't seem to understand the action of a user adding a comment to an article. I've attached a screenshot.
<img width="400" alt="image" src="https://github.com/Markus-Rost/discord-wiki-bot/assets/123885349/4ccd728c-9e79-4a04-a75f-55a5a4c9a06b">

**Comment by Markus-Rost** [comment]
Moved to [chicken-riders/RcGcDb#48](https://gitlab.com/chicken-riders/RcGcDb/-/issues/48) and [piotrex43/RcGcDw#274](https://gitlab.com/piotrex43/RcGcDw/-/issues/274)
