### ISSUE TITLE
Allow users to be verified while being banned in the wiki but With Restricted/Limited access while being blocked

### ISSUE THREAD

**Issue by GodlyFirecracker** [Markus-Rost/discord-wiki-bot#543]
Why not,when you got blocked,it is unfair when you met the requirement for editor verification 

Also Limited access means once the account is verified while being blocked,Certain features may be unavailable for them until the block duration is up/unblocked
The role could be:Verified Blocked Editor(will remove once after block duration is up or being unblocked)

**Comment by Friskygote** [comment]
I believe that wiki administrators would rather not have users verify while being banned on wiki. Often verification function gives various roles like access to additional editor only channels, banning on the wikis is usually a last resort option to prevent further damage to the wiki.

I believe current default is appropriate and Discord administrators can always choose to overwrite it by giving the roles by themselves.

**Comment by GodlyFirecracker** [comment]
Ok,but maybe this can be a toggleable like feature instead,but however it will say like this
Enable verification while being banned in the wiki(not recommended)

**Comment by Markus-Rost** [comment]
Considering that this seems not like something anyone would be interested and and that blocked users generally aren't able to verify themselves anyway, this won't be added.
If you want to give blocked users a different role, you can do that manually when their verification returns the blocked error.
