### ISSUE TITLE
Possible problem with Wiki-Bot and RCGcDb

### ISSUE THREAD

**Issue by TreeIsLife2** [Markus-Rost/discord-wiki-bot#82]
https://gitlab.com/chicken-riders/RcGcDb/-/issues/26 - This can be also problem with Wiki-Bot, as rc was set-up from Wiki Bot.

**Comment by Friskygote** [comment]
I don't think it's a problem with Wiki-Bot, the database had data saved correctly, and that's all that Wiki-Bot should partake in sending the messages, it was RcGcDb which somehow sent the messages to wrong webhook. I'm currently investigating RcGcDb with similar but not exact environment and circumstances. I'll update my findings (if there are any) in the linked RcGcDb issue.

**Comment by TreeIsLife2** [comment]
Ok
