### ISSUE TITLE
Connection to GitHub wikis?

### ISSUE THREAD

**Issue by HausReport** [Markus-Rost/discord-wiki-bot#84]
Hi,

I tried the following: 

!wiki settings wiki https://github.com/HausReport/ClubRaiders/wiki/

and got

@You, please provide a valid link to a MediaWiki site, like a Gamepedia or Fandom wiki!
Use !wiki settings wiki <link> to change the default wiki.

I wonder if there's a way to config the bot to work with GitHub wikis?

**Comment by Sidemen19** [comment]
Uh, GitHub wikis aren't MediaWiki sites. Logging new GitHub changes isn't in the scope of Wiki-Bot and very irrelevant to the bot. If you want to set up GitHub-to-Discord logging, you should read https://gist.github.com/jagrosh/5b1761213e33fc5b54ec7f6379034a22

**Comment by Markus-Rost** [comment]
As Github wikis aren't based on MediaWiki the bot can't support them and I don't plan to add support for them either.
